import { ToStringOpts } from "ts-poet/build/Code";

export function getTsPoetOpts(
  tsProtoVersion: string,
  protocVersion: string,
  fileName?: string,
): ToStringOpts {
  return {
    // Comment block at the top of every source file, since these comments require specific
    // syntax incompatible with ts-poet, we will hard-code the string and prepend to the
    // generator output.
    prefix: `// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
${fileName ? `// source: ${fileName}` : ""}

    /* eslint-disable */`,
    dprintOptions: { preferSingleLine: true, lineWidth: 120 },
  };
}
