import { ToStringOpts } from "ts-poet/build/Code";

export enum LongOption {
  NUMBER = "number",
  LONG = "long",
  STRING = "string",
  BIGINT = "bigint",
}

export enum DateOption {
  DATE = "date",
  STRING = "string",
  STRING_NANO = "string-nano",
  TIMESTAMP = "timestamp",
}

export enum JsonTimestampOption {
  RFC3339 = "rfc3339",
  RAW = "raw",
}

export enum ServiceOption {
  GENERIC = "generic-definitions",
  DEFAULT = "default",
  NONE = "none",
}

export type Options = {
};

export function defaultOptions(): Options {
  return {
  };
}

export function optionsFromParameter(parameter: string | undefined): Options {
  const options = defaultOptions();
  if (parameter) {
    const parsed = parseParameter(parameter);
    Object.assign(options, parsed);
  }

  return options;
}

// A very naive parse function, eventually could/should use iots/runtypes
function parseParameter(parameter: string): Options {
  const options = { M: {} } as any;
  parameter.split(",").forEach((param) => {
    // same as protoc-gen-go https://github.com/protocolbuffers/protobuf-go/blob/bf9455640daabb98c93b5b5e71628f3f813d57bb/compiler/protogen/protogen.go#L168-L171
    const optionSeparatorPos = param.indexOf("=");
    const key = param.substring(0, optionSeparatorPos);
    const value = parseParamValue(param.substring(optionSeparatorPos + 1));
    if (key.charAt(0) === "M") {
      if (typeof value !== "string") {
        console.warn(`ignoring invalid M option: '${param}'`);
      } else {
        const mKey = key.substring(1);
        if (options.M[mKey]) {
          console.warn(`received conflicting M options: '${param}' will override 'M${mKey}=${options.M[mKey]}'`);
        }
        if (param.endsWith(".ts")) {
          console.warn(`received M option '${param}' ending in '.ts' this is usually a mistake`);
        }
        options.M[mKey] = value;
      }
    } else if (options[key]) {
      options[key] = [options[key], value];
    } else {
      options[key] = value;
    }
  });
  return options;
}

function parseParamValue(value: string): string | boolean {
  return value === "true" ? true : value === "false" ? false : value;
}

export function getTsPoetOpts(
  options: Options,
  tsProtoVersion: string,
  protocVersion: string,
  fileName?: string,
): ToStringOpts {
  return {
    // Comment block at the top of every source file, since these comments require specific
    // syntax incompatible with ts-poet, we will hard-code the string and prepend to the
    // generator output.
    prefix: `// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
${fileName ? `// source: ${fileName}` : ""}

    /* eslint-disable */`,
    dprintOptions: { preferSingleLine: true, lineWidth: 120 },
  };
}
